TELEGRAM_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

SCAN_INTERVAL = 30

TOP_COINS = [
"BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
"ADAUSDT","DOGEUSDT","AVAXUSDT","LINKUSDT","DOTUSDT",
"TRXUSDT","MATICUSDT","LTCUSDT","ATOMUSDT","ETCUSDT",
"FILUSDT","APTUSDT","NEARUSDT","ARBUSDT","OPUSDT",
"SUIUSDT","PEPEUSDT","BONKUSDT","INJUSDT"
]
