TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

SCAN_INTERVAL = 30

TOP_COINS = [
"BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
"ADAUSDT","DOGEUSDT","AVAXUSDT","LINKUSDT","MATICUSDT",
"DOTUSDT","TRXUSDT","LTCUSDT","ATOMUSDT","ETCUSDT",
"FILUSDT","NEARUSDT","APTUSDT","ARBUSDT","OPUSDT",
"SUIUSDT","PEPEUSDT","BONKUSDT"
]
